# frozen_string_literal: true

tap "d/tap-rust", "https://git@git.sr.ht/~declantsien/guix-channel/"
brew 'autoconf'
brew 'coreutils'
brew 'dbus'
brew 'expat'
brew 'gcc'
brew 'gmp'
brew 'gnu-sed'
brew 'gnutls'
brew 'jansson'
brew 'libffi'
brew 'libgccjit'
brew 'libiconv'
brew 'librsvg'
brew 'libtasn1'
brew 'libunistring'
brew 'libxml2'
brew 'little-cms2'
brew 'mailutils'
brew 'make'
brew 'ncurses'
brew 'nettle'
brew 'pkg-config'
brew 'sqlite'
brew 'texinfo'
brew 'tree-sitter'
brew 'zlib'
brew 'rust-nightly-2022-10-24'
